language: rust
addons:
  apt:
    packages:
     - capnproto
     - libgl1-mesa-dev
  homebrew:
    packages: capnp
    update: true
install:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install capnproto; fi
before_script:
  - if [ $SKIP_FORMAT_CHECK = 0 ]; then rustup component add rustfmt; fi
  - if [ $SKIP_CLIPPY = 0 ]; then rustup component add clippy; fi
script:
  - cargo build --verbose --all
  - if [ $SKIP_FORMAT_CHECK = 0 ]; then cargo fmt --all -- --check; fi
  - if [ $SKIP_CLIPPY = 0 ]; then cargo clippy -- -D warnings; fi
matrix:
  include:
    - name: "Windows Stable (MSVC)"
      rust: stable-msvc
      os: windows
      env: SKIP_FORMAT_CHECK=1 SKIP_CLIPPY=1
    - name: "OSX Stable"
      rust: stable
      os: osx
      env: SKIP_FORMAT_CHECK=1 SKIP_CLIPPY=1
    - name: "Linux Stable"
      rust: stable
      os: linux
      env: SKIP_FORMAT_CHECK=1 SKIP_CLIPPY=1
